[%
    T = {
        title = "IntranetUserJS: Add links to bibliographic records in Finna",
        description = "Adds links to bibliographic records in Finna to the Cart, search results, and Normal view. Add a custom URL prefix in the configuration. (Local databases)",
        home = "Home",
        plugins = "Plugins",
        view = "View JS plugin",
        configuration = "Configuration",
        back = "Back",
        save = "Save configuration",
        config_label = "Finna link prefix / Finna URL (e.g. https://siilinjarvenkirjasto.finna.fi/Record/siilinjarvi):",
        upgrade_status = "Upgrade status",
        last_upgraded = "Plugin was last upgraded on",
        never_upgraded = "Plugin has never been upgraded."
    }
%]