[%
    T = {
        title = "IntranetUserJS: Lisää linkit tietueeseen Finnassa",
        description = "Finna-verkkokirjastolinkkien lisääminen ostoskoriin (cart), hakutuloksiin ja tietuenäytölle. Konfiguroitava. Lisää kimppakohtainen URL-alkuosa määrittelyssä. (Paikalliskannat)",
        home = "Etusivu",
        plugins = "Liitännäiset",
        view = "Näytä JS-työkalu",
        configuration = "Määritys",
        back = "Takaisin",
        save = "Tallenna määritys",
        config_label = "Finna-linkin alkuosa/Finnan URL (esim. https://siilinjarvenkirjasto.finna.fi/Record/siilinjarvi):",
        upgrade_status = "Päivityksen tila",
        last_upgraded = "Liitännäinen päivitettiin viimeksi tähän järjestelmään",
        never_upgraded = "Liitännäistä ei ole koskaan päivitetty."
    }
%]