[%
    T = {
        title = "IntranetUserJS: Lisää linkit kuvailutietueisiin Finna-verkkokirjastoon",
        description = "Lisää linkit kuvailutietueisiin Finna-verkkokirjastoon Korissa, hakutuloksissa ja tietuenäytölle. Lisää kimppakohtainen URL-alkuosa määrittelyssä. (Paikalliskannat)",
        home = "Etusivu",
        plugins = "Liitännäiset",
        view = "Näytä JS-Liitännäinen",
        configuration = "Määritykset",
        back = "Takaisin",
        save = "Tallenna määritykset",
        config_label = "Finna-linkin alkuosa/Finnan URL (esim. https://siilinjarvenkirjasto.finna.fi/Record/siilinjarvi):",
        upgrade_status = "Päivityksen tila",
        last_upgraded = "Liitännäinen päivitettiin viimeksi",
        never_upgraded = "Liitännäistä ei ole koskaan päivitetty."
    }
%]