[%
    T = {
        title = "IntranetUserJS: Lägg till länkar till posten i Finna",
        description = "Lägger till Finna-länkar i kundvagnen (cart), i sökresultaten och i postvyn. Konfigurerbar. Lägg till det instansspecifika URL-prefixet i konfigurationen. (Lokal institutionsfunktion)",
        home = "Hem",
        plugins = "Plugins",
        view = "Visa JS-verktyget",
        configuration = "Inställningar",
        back = "Tillbaka",
        save = "Spara inställningar",
        config_label = "Finna-länkens början / Finna-URL (t.ex. https://siilinjarvenkirjasto.finna.fi/Record/siilinjarvi):",
        upgrade_status = "Uppgraderingsstatus",
        last_upgraded = "Plugin uppgraderades senast på detta system den",
        never_upgraded = "Plugin har aldrig uppgraderats."
    }
%]