[%
    T = {
        title = "IntranetUserJS: Lägger till länkar till bibliografiska poster i Finna",
        description = "Lägger till länkar till bibliografiska poster i Finna i Minneslistan, sökresultaten och Normal-vyn. Lägg till ett anpassat URL-prefix i konfigurationen. (Lokala databaser)",
        home = "Hem",
        plugins = "Plugins",
        view = "Visa JS-plugin",
        configuration = "Inställningar",
        back = "Tillbaka",
        save = "Spara inställningar",
        config_label = "Finna-länkens början / Finna-URL (t.ex. https://siilinjarvenkirjasto.finna.fi/Record/siilinjarvi):",
        upgrade_status = "Uppgraderingsstatus",
        last_upgraded = "Plugin uppgraderades senast",
        never_upgraded = "Plugin har aldrig uppgraderats."
    }
%]